#!/usr/bin/env bash
# IPK Browser MCP - Credential Setup
# Run this in your terminal (NOT in Claude Code) to securely configure credentials.
#
# Usage:
#   bash scripts/setup.sh
#   OR after plugin install:
#   bash ~/.claude/plugins/cache/*/ipk-browser-mcp/*/scripts/setup.sh

set -euo pipefail

CONFIG_DIR="$HOME/.config/ipk-browser-mcp"
ENV_FILE="$CONFIG_DIR/.env"

echo "==================================="
echo " IPK Browser MCP - Credential Setup"
echo "==================================="
echo ""

# Check if already configured
if [ -f "$ENV_FILE" ]; then
    echo "Existing configuration found at: $ENV_FILE"
    read -p "Overwrite? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

# Collect credentials
read -p "IPK Username (groupware ID): " IPK_USERNAME
read -sp "IPK Password: " IPK_PASSWORD
echo ""
read -p "IPK Base URL [https://gw.ip-korea.org]: " IPK_BASE_URL
IPK_BASE_URL="${IPK_BASE_URL:-https://gw.ip-korea.org}"

# Optional settings
echo ""
echo "Optional settings (press Enter to skip):"
read -p "Your name (for form auto-fill): " IPK_USER_NAME
read -p "Your department: " IPK_USER_DEPT

# Write config
mkdir -p "$CONFIG_DIR"
cat > "$ENV_FILE" << ENVEOF
# IPK Groupware Credentials
# Generated by ipk-browser-mcp setup on $(date -Iseconds)
# DO NOT commit this file to git!

IPK_USERNAME=${IPK_USERNAME}
IPK_PASSWORD=${IPK_PASSWORD}
IPK_BASE_URL=${IPK_BASE_URL}
ENVEOF

# Add optional settings if provided
[ -n "$IPK_USER_NAME" ] && echo "IPK_USER_NAME=${IPK_USER_NAME}" >> "$ENV_FILE"
[ -n "$IPK_USER_DEPT" ] && echo "IPK_USER_DEPT=${IPK_USER_DEPT}" >> "$ENV_FILE"

chmod 600 "$ENV_FILE"

echo ""
echo "Setup complete!"
echo "  Config saved to: $ENV_FILE (permissions: 600)"
echo "  Restart Claude Code to activate."
echo ""
echo "To update later, run this script again."
